# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - test/**
      - pubspec.yaml
    builders:
      pubspec_generator:
        options:
          output: lib/src/constants/pubspec.yaml.g.dart
      drift_dev:
        options:
          named_parameters: true
          raw_result_set_data: true
          store_date_time_values_as_text: true