Map<String, Object> sharedPrefsDefaults = <String, Object>{
  'sound': true,
  'beep': true,
  'voice': true,
  'voiceName': true,
  'volume': 1.0,
  'pitch': 1.0,
  'rate': 0.5,
  'language': 'ru-RU',
  'recentFile': '',
  'wakelock': true,
  'startFab': true,
  'startFabSize': 75.0,
  'finishFab': true,
  'finishFabSize': 75.0,
  'countdown': false,
  'countdownSize': 75.0,
  'countdownLeft': 0.0,
  'countdownTop': 0.0,
  'countdownAtStartTime': true,
  'checkUpdates': true,
  'hideMarked': true,
  'hideNumbers': false,
  'hideManual': false,
  'reconnect': true,
  'finishDelay': 350,
  'substituteNumbers': false,
  'substituteNumbersDelay': 500,
  'logLimit': -1,
// appTheme: themeFromString(prefs.getString('theme')),
  'previousVersion': '0.0.0',
};
