// Mocks generated by Mockito 5.4.4 from annotations
// in entime/test/src/feature/app_info/logic/app_info_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:device_info_plus/src/model/android_device_info.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAndroidBuildVersion_0 extends _i1.SmartFake
    implements _i2.AndroidBuildVersion {
  _FakeAndroidBuildVersion_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AndroidDeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAndroidDeviceInfo extends _i1.Mock implements _i2.AndroidDeviceInfo {
  MockAndroidDeviceInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AndroidBuildVersion get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _FakeAndroidBuildVersion_0(
          this,
          Invocation.getter(#version),
        ),
      ) as _i2.AndroidBuildVersion);

  @override
  String get board => (super.noSuchMethod(
        Invocation.getter(#board),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#board),
        ),
      ) as String);

  @override
  String get bootloader => (super.noSuchMethod(
        Invocation.getter(#bootloader),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#bootloader),
        ),
      ) as String);

  @override
  String get brand => (super.noSuchMethod(
        Invocation.getter(#brand),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#brand),
        ),
      ) as String);

  @override
  String get device => (super.noSuchMethod(
        Invocation.getter(#device),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#device),
        ),
      ) as String);

  @override
  String get display => (super.noSuchMethod(
        Invocation.getter(#display),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#display),
        ),
      ) as String);

  @override
  String get fingerprint => (super.noSuchMethod(
        Invocation.getter(#fingerprint),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#fingerprint),
        ),
      ) as String);

  @override
  String get hardware => (super.noSuchMethod(
        Invocation.getter(#hardware),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#hardware),
        ),
      ) as String);

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
      ) as String);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get manufacturer => (super.noSuchMethod(
        Invocation.getter(#manufacturer),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
      ) as String);

  @override
  String get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
      ) as String);

  @override
  String get product => (super.noSuchMethod(
        Invocation.getter(#product),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#product),
        ),
      ) as String);

  @override
  List<String> get supported32BitAbis => (super.noSuchMethod(
        Invocation.getter(#supported32BitAbis),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get supported64BitAbis => (super.noSuchMethod(
        Invocation.getter(#supported64BitAbis),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get supportedAbis => (super.noSuchMethod(
        Invocation.getter(#supportedAbis),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#tags),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  bool get isPhysicalDevice => (super.noSuchMethod(
        Invocation.getter(#isPhysicalDevice),
        returnValue: false,
      ) as bool);

  @override
  List<String> get systemFeatures => (super.noSuchMethod(
        Invocation.getter(#systemFeatures),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get serialNumber => (super.noSuchMethod(
        Invocation.getter(#serialNumber),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#serialNumber),
        ),
      ) as String);

  @override
  bool get isLowRamDevice => (super.noSuchMethod(
        Invocation.getter(#isLowRamDevice),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
