name: Flutter PR

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "android/**"
      - "ios/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "android/**"
      - "ios/**"

jobs:
  build:
    name: Analyze project source and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests and collect coverage
        run: flutter test --coverage test/

      - name: Clean coverage
        run: sudo apt-get -y install lcov
        run: lcov -r coverage/lcov.info -o coverage/lcov.info "lib/**.freezed.dart" "lib/**.g.dart" "lib/src/common/localization/generated/**.dart"
        
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.0
