name: Analyze and run tests

on:
  push:
    branches:
      - master
    paths:
      - "**.dart"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "analysis_options.yaml"
      - "android/**"
      - "ios/**"
      - "lib/src/common/localization/**"
      - "**.drift"
      - ".github/actions/**"
      - ".github/workflows/**"
      - "!**.g.dart"
      - "!**.freezed.dart"
  pull_request:
    branches:
      - master
    paths:
      - "**.dart"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "analysis_options.yaml"
      - "android/**"
      - "ios/**"
      - "lib/src/common/localization/**"
      - "**.drift"
      - ".github/actions/**"
      - ".github/workflows/**"
      - "!**.g.dart"
      - "!**.freezed.dart"

jobs:
  build:
    name: Analyze project source and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'stable', 'beta', 'main' or 'master'
          cache: true

      - uses: ./.github/actions/flutter-quality
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
